apiVersion: v1
kind: Service
metadata:
  name: test-model
  namespace: default
  labels:
    app: test-model
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: test-model